'use client'
import type { Metadata } from 'next'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import './globals.css'
import BasicExample from '@/components/navbar'
// import { Container } from 'postcss'
import { Container } from 'react-bootstrap'

const inter = Inter({ subsets: ['latin'] })

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <BasicExample />
        <Container>
          {children}
        </Container>
        
        </body>
    </html>
  )
}
